console.log('fail')

require('assert').ok(false,'INTENSIONAL FAIL')
